ABook/config/routes.rb
ABook::Application.routes.draw do
  resources :abooks

root 'abooks#index'

  

end

ABook/app/models/abook.rb
class Abook < ActiveRecord::Base

require 'zip_valid'

#first name validation
validates_presence_of :first_name
validates_format_of :first_name, :with => /\A[a-zA-Z]+\z/ , :message => ": Only letters are permitted"


#last name validation
validates_presence_of :last_name
validates_format_of :last_name, :with => /\A[a-zA-Z]+\z/ , :message => ": Only letters are permitted"


#email validation
validates_presence_of :email
validates_format_of :email, :with => /\A([-a-z0-9!\#$%&'*+\/=?^_`{|}~]+\.)*[-a-z0-9!\#$%&'*+\/=?^_`{|}~]+@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
validates_uniqueness_of :email, :message => ": Email already in use"

#zip code validation
validates_presence_of :zipcode
validates_format_of :zipcode, :with => /\A[0-9]{5}\z/

#Favorite color validation

validates_presence_of :fav_color

#validates_format_of :fav_color, :with => /\A[a-zA-z\d_]+\z/, :message => ": Please do not use spaces in favorite color" 

validate :check_zip
#validate :check_color
def check_zip
	if !(ValidZip.is_legal(self.zipcode))
		errors.add :zipcode, "is not a valid zipcode"
	end

#def check_color
#	if !{ValidColor.islegal(self.fav_color))
#		errors.add :fav_color, "is not a valid favorite color"
#	end	
#end

end
end

ABook/app/controllers/abooks_controller.rb
class AbooksController < ApplicationController
  before_action :set_abook, only: [:show, :edit, :update, :destroy]

  # GET /abooks
  # GET /abooks.json
  def index
    @abooks = Abook.all
  end

  # GET /abooks/1
  # GET /abooks/1.json
  def show
  end

  # GET /abooks/new
  def new
    @abook = Abook.new
  end

  # GET /abooks/1/edit
  def edit
  end

  # POST /abooks
  # POST /abooks.json
  def create
    @abook = Abook.new(abook_params)

    respond_to do |format|
      if @abook.save
        format.html { redirect_to @abook, notice: 'Abook was successfully created.' }
        format.json { render action: 'show', status: :created, location: @abook }
      else
        format.html { render action: 'new' }
        format.json { render json: @abook.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /abooks/1
  # PATCH/PUT /abooks/1.json
  def update
    respond_to do |format|
      if @abook.update(abook_params)
        format.html { redirect_to @abook, notice: 'Abook was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @abook.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /abooks/1
  # DELETE /abooks/1.json
  def destroy
    @abook.destroy
    respond_to do |format|
      format.html { redirect_to abooks_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_abook
      @abook = Abook.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def abook_params
      params.require(:abook).permit(:first_name, :last_name, :email, :zipcode, :fav_color)
    end
end

ABook/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

ABook/app/helpers/abooks_helper.rb
module AbooksHelper
end

ABook/app/helpers/application_helper.rb
module ApplicationHelper
end

ABook/app/views/abooks/_form.html.erb
<%= form_for(@abook) do |f| %>
  <% if @abook.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@abook.errors.count, "error") %> prohibited this abook from being saved:</h2>

      <ul>
      <% @abook.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :zipcode %><br>
    <%= f.text_field :zipcode %>
  </div>
  <div class="field">
    <%= f.label :fav_color %><br>
	<%= f.select :fav_color, ["AliceBlue","AntiqueWhite","Aqua","Aquamarine","Azure","Beige","Bisque","Black","BlanchedAlmond","Blue","BlueViolet","Brown","BurlyWood","CadetBlue","Chartreuse","Chocolate","Coral","CornflowerBlue","Cornsilk","Crimson","Cyan","DarkBlue","DarkCyan","DarkGoldenRod","DarkGray","DarkGreen","DarkKhaki","DarkMagenta","DarkOliveGreen","DarkOrange","DarkOrchid","DarkRed","DarkSalmon","DarkSeaGreen","DarkSlateBlue","DarkSlateGray","DarkTurquoise","DarkViolet","DeepPink","DeepSkyBlue","DimGray","DodgerBlue","FireBrick","FloralWhite","ForestGreen","Fuchsia","Gainsboro","GhostWhite","Gold","GoldenRod","Gray","Green","GreenYellow","HoneyDew","HotPink","IndianRed","Indigo","Ivory","Khaki","Lavender","LavenderBlush","LawnGreen","LemonChiffon","LightBlue","LightCoral","LightCyan","LightGoldenRodYellow","LightGray","LightGreen","LightPink","LightSalmon","LightSeaGreen","LightSkyBlue","LightSlateGray","LightSteelBlue","LightYellow","Lime","LimeGreen","Linen","Magenta","Maroon","MediumAquaMarine","MediumBlue","MediumOrchid","MediumPurple","MediumSeaGreen","MediumSlateBlue","MediumSpringGreen","MediumTurquoise","MediumVioletRed","MidnightBlue","MintCream","MistyRose","Moccasin","NavajoWhite","Navy","OldLace","Olive","OliveDrab","Orange","OrangeRed","Orchid","PaleGoldenRod","PaleGreen","PaleTurquoise","PaleVioletRed","PapayaWhip","PeachPuff","Peru","Pink","Plum","PowderBlue","Purple","Red","RosyBrown","RoyalBlue","SaddleBrown","Salmon","SandyBrown","SeaGreen","SeaShell","Sienna","Silver","SkyBlue","SlateBlue","SlateGray","Snow","SpringGreen","SteelBlue","Tan","Teal","Thistle","Tomato","Turquoise","Violet","Wheat","White","WhiteSmoke","Yellow","YellowGreen"] %></div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

ABook/app/views/abooks/edit.html.erb
<body>
<h1>Editing abook</h1>

<p1><%= render 'form' %></p1>

<table>
<tbody>
<tr>
<td><%= link_to 'Show', @abook %></td>
<td><%= link_to 'Back', abooks_path %></td>
</tr>
</tbody>
</table>
</body>

ABook/app/views/abooks/index.html.erb
<body>
<h1><%=image_tag("chibi1.jpg", alt: "Address Book")%><br>
<br>Your Local Address Book</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Zip code</th>
      <th>Favorite color</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @abooks.each do |abook| %>
      <tr>
        <td><%= abook.first_name.titleize %></td>
        <td><%= abook.last_name.titleize %></td>
        <td><%= abook.email.titleize %></td>
        <td><%= abook.zipcode %></td>
        <td><%= abook.fav_color %></td>
        <td bgcolor= <%= abook.fav_color %>>  This is their favorite color</td>
	<td><%= link_to 'Show', abook %></td>
        <td><%= link_to 'Edit', edit_abook_path(abook) %></td>
        <td><%= link_to 'Destroy', abook, method: :delete, data: { confirm: 'Are you sure you want to delete this entry?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<table id="1">
	<thead>
<tr>
	<th id="1"><%= link_to 'Add new entry', new_abook_path %></th>

</body>

ABook/app/views/abooks/new.html.erb
<h1>Create New entry</h1>

<p1><%= render 'form' %></p1>

<table>
<tbody>
<tr>
<td><%= link_to 'Back', abooks_path %></td>
</tr>
</tbody>
</table>
</body>

ABook/app/views/abooks/show.html.erb
<body>
<h1> Viewing User </h1>

<p id="notice"><%= notice %></p>
<p1>
<center>
 <strong>First name:</strong> <%= @abook.first_name.titleize %> <br>
  <strong>Last name:</strong> <%= @abook.last_name.titleize %> <br>
  <strong>Email:</strong> <%= @abook.email.titleize %> <br>
  <strong>Zip code:</strong> <%= @abook.zipcode %> <br>
  <strong>Favorite color:</strong> <%= @abook.fav_color%>
</center>
<br>
</p1>

<table>
<tbody>
<tr>
<td><%= link_to 'Show', @abook %></td>
<td><%= link_to 'Back', abooks_path %></td>
</tr>
</tbody>
</table>
</body>

ABook/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ABook</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>